### ISSUE TITLE
Can't assign to multiple

### ISSUE THREAD

**Issue by JeroenMoolenschot** [joomdev/jd-social-share#1]
I would like to show the buttons on all (Joomla) articles in the category "blog" and only assign to the page type "articles" (so not to the blog/list view).
When i select both the sharing buttons appears on all pages. 
When i select only the category or only the page type it works, but it would be nice if i can select both.

**Comment by chetanmadaan** [comment]
Hi @Joomill, We are aware of some minor assignment issues in the plugin. Will see if we can get this one straightened out.
